PIPELINE_TYPE_LIT = 0
PIPELINE_TYPE_UNLIT = 1
PIPELINE_TYPE_POST = 2
PIPELINE_TYPE_CRT = 3
PIPELINE_TYPE_SCREEN = 4
PIPELINE_TYPE_BLOOM_BLUR = 5
PIPELINE_TYPE_BLOOM_TRANSFER = 6
PIPELINE_TYPE_BLOOM_RESOLVE = 7
PIPELINE_TYPE_PARTICLE = 8

UNIFORM_TYPE_PROJECTION = 0
UNIFORM_TYPE_ALBEDO = 1
UNIFORM_TYPE_AMBIENT_OCCLUSION = 2
UNIFORM_TYPE_SPECULAR = 3
UNIFORM_TYPE_NORMAL = 4
UNIFORM_TYPE_MATERIAL_COUNT = 5
UNIFORM_TYPE_MATERIAL = 6
UNIFORM_TYPE_BRIGHT_MATERIAL = 7
UNIFORM_TYPE_MODEL = 8
UNIFORM_TYPE_VIEW = 9
UNIFORM_TYPE_LIGHT0_POS = 10
UNIFORM_TYPE_LIGHT0_COLOR = 11
UNIFORM_TYPE_LIGHT0_STRENGTH = 12
UNIFORM_TYPE_LIGHT1_POS = 13
UNIFORM_TYPE_LIGHT1_COLOR = 14
UNIFORM_TYPE_LIGHT1_STRENGTH = 15
UNIFORM_TYPE_LIGHT2_POS = 16
UNIFORM_TYPE_LIGHT2_COLOR = 17
UNIFORM_TYPE_LIGHT2_STRENGTH = 18
UNIFORM_TYPE_LIGHT3_POS = 19
UNIFORM_TYPE_LIGHT3_COLOR = 20
UNIFORM_TYPE_LIGHT3_STRENGTH = 21
UNIFORM_TYPE_LIGHT4_POS = 22
UNIFORM_TYPE_LIGHT4_COLOR = 23
UNIFORM_TYPE_LIGHT4_STRENGTH = 24
UNIFORM_TYPE_LIGHT5_POS = 25
UNIFORM_TYPE_LIGHT5_COLOR = 26
UNIFORM_TYPE_LIGHT5_STRENGTH = 27
UNIFORM_TYPE_LIGHT6_POS = 28
UNIFORM_TYPE_LIGHT6_COLOR = 29
UNIFORM_TYPE_LIGHT6_STRENGTH = 30
UNIFORM_TYPE_LIGHT7_POS = 31
UNIFORM_TYPE_LIGHT7_COLOR = 32
UNIFORM_TYPE_LIGHT7_STRENGTH = 33
UNIFORM_TYPE_CAMERA_POS = 34
UNIFORM_TYPE_MATERIAL_INDEX = 35
UNIFORM_TYPE_TINT = 36

SHADERS = (
    PIPELINE_TYPE_LIT, PIPELINE_TYPE_UNLIT,
    PIPELINE_TYPE_POST, PIPELINE_TYPE_CRT,
    PIPELINE_TYPE_SCREEN, PIPELINE_TYPE_BLOOM_BLUR,
    PIPELINE_TYPE_BLOOM_TRANSFER, PIPELINE_TYPE_BLOOM_RESOLVE,
    PIPELINE_TYPE_PARTICLE)

VERTEX_MODULE_FILENAMES = {
    PIPELINE_TYPE_LIT: "shaders/vertex.txt",
    PIPELINE_TYPE_UNLIT: "shaders/vertex_light.txt",
    PIPELINE_TYPE_POST: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_CRT: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_SCREEN: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_BLOOM_BLUR: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_BLOOM_TRANSFER: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_BLOOM_RESOLVE: "shaders/simple_post_vertex.txt",
    PIPELINE_TYPE_PARTICLE: "shaders/particle_vertex.txt",
}

FRAGMENT_MODULE_FILENAMES = {
    PIPELINE_TYPE_LIT: "shaders/fragment.txt",
    PIPELINE_TYPE_UNLIT: "shaders/fragment_light.txt",
    PIPELINE_TYPE_POST: "shaders/post_fragment.txt",
    PIPELINE_TYPE_CRT: "shaders/crt_fragment.txt",
    PIPELINE_TYPE_SCREEN: "shaders/screen_fragment.txt",
    PIPELINE_TYPE_BLOOM_BLUR: "shaders/bloom_blur_fragment.txt",
    PIPELINE_TYPE_BLOOM_TRANSFER: "shaders/bloom_transfer_fragment.txt",
    PIPELINE_TYPE_BLOOM_RESOLVE: "shaders/bloom_resolve_fragment.txt",
    PIPELINE_TYPE_PARTICLE: "shaders/particle_fragment.txt"
}

UNIFORM_NAMES = {
    PIPELINE_TYPE_LIT: {
        UNIFORM_TYPE_PROJECTION: "projection",
        UNIFORM_TYPE_ALBEDO: "material.albedo",
        UNIFORM_TYPE_AMBIENT_OCCLUSION: "material.ao",
        UNIFORM_TYPE_SPECULAR: "material.specular",
        UNIFORM_TYPE_NORMAL: "material.normal",
        UNIFORM_TYPE_MATERIAL_COUNT: "material_count",
        UNIFORM_TYPE_MODEL: "model",
        UNIFORM_TYPE_VIEW: "view",
        UNIFORM_TYPE_LIGHT0_POS: "lightPos[0]",
        UNIFORM_TYPE_LIGHT0_COLOR: "lights[0].color",
        UNIFORM_TYPE_LIGHT0_STRENGTH: "lights[0].strength",
        UNIFORM_TYPE_LIGHT1_POS: "lightPos[1]",
        UNIFORM_TYPE_LIGHT1_COLOR: "lights[1].color",
        UNIFORM_TYPE_LIGHT1_STRENGTH: "lights[1].strength",
        UNIFORM_TYPE_LIGHT2_POS: "lightPos[2]",
        UNIFORM_TYPE_LIGHT2_COLOR: "lights[2].color",
        UNIFORM_TYPE_LIGHT2_STRENGTH: "lights[2].strength",
        UNIFORM_TYPE_LIGHT3_POS: "lightPos[3]",
        UNIFORM_TYPE_LIGHT3_COLOR: "lights[3].color",
        UNIFORM_TYPE_LIGHT3_STRENGTH: "lights[3].strength",
        UNIFORM_TYPE_LIGHT4_POS: "lightPos[4]",
        UNIFORM_TYPE_LIGHT4_COLOR: "lights[4].color",
        UNIFORM_TYPE_LIGHT4_STRENGTH: "lights[4].strength",
        UNIFORM_TYPE_LIGHT5_POS: "lightPos[5]",
        UNIFORM_TYPE_LIGHT5_COLOR: "lights[5].color",
        UNIFORM_TYPE_LIGHT5_STRENGTH: "lights[5].strength",
        UNIFORM_TYPE_LIGHT6_POS: "lightPos[6]",
        UNIFORM_TYPE_LIGHT6_COLOR: "lights[6].color",
        UNIFORM_TYPE_LIGHT6_STRENGTH: "lights[6].strength",
        UNIFORM_TYPE_LIGHT7_POS: "lightPos[7]",
        UNIFORM_TYPE_LIGHT7_COLOR: "lights[7].color",
        UNIFORM_TYPE_LIGHT7_STRENGTH: "lights[7].strength",
        UNIFORM_TYPE_CAMERA_POS: "viewPos",
        UNIFORM_TYPE_MATERIAL_INDEX: "material_index",
    },

    PIPELINE_TYPE_UNLIT: {
        UNIFORM_TYPE_PROJECTION: "projection",
        UNIFORM_TYPE_MATERIAL: "imageTexture",
        UNIFORM_TYPE_MATERIAL_COUNT: "material_count",
        UNIFORM_TYPE_MODEL: "model",
        UNIFORM_TYPE_VIEW: "view",
        UNIFORM_TYPE_TINT: "tint",
        UNIFORM_TYPE_MATERIAL_INDEX: "material_index",
    },

    PIPELINE_TYPE_SCREEN: {
        UNIFORM_TYPE_MATERIAL: "material",
        UNIFORM_TYPE_TINT: "tint",
    },

    PIPELINE_TYPE_BLOOM_BLUR: {
        UNIFORM_TYPE_MATERIAL: "material",
        UNIFORM_TYPE_BRIGHT_MATERIAL: "bright_material",
    },

    PIPELINE_TYPE_BLOOM_TRANSFER: {
        UNIFORM_TYPE_MATERIAL: "material",
        UNIFORM_TYPE_BRIGHT_MATERIAL: "bright_material",
    },

    PIPELINE_TYPE_BLOOM_RESOLVE: {
        UNIFORM_TYPE_MATERIAL: "material",
        UNIFORM_TYPE_BRIGHT_MATERIAL: "bright_material",
    },

    PIPELINE_TYPE_PARTICLE: {
        UNIFORM_TYPE_VIEW: "view",
        UNIFORM_TYPE_PROJECTION: "projection",
    },
}
