#include <iostream>
#include <fstream>
#include <sstream>

#include <json/json.h>
/*
	Skeletal Animation.
	Stage 1: Json files.
*/

int main() {

	std::ifstream myJsonFile;
	//Open the file as text
	myJsonFile.open("src/my_cube.gltf");
	std::string line;

	//Read line by line
	while (std::getline(myJsonFile, line)) {
		std::cout << line << std::endl;
	}
	myJsonFile.close();

	//Open the file as binary
	myJsonFile.open("src/my_cube.gltf", std::ios::binary);
	//To hold the parsed json data
	Json::Value parsedContents;

	//Attempt to read and parse
	myJsonFile >> parsedContents;

	//Examine contents.
    Json::Value assetDescription = parsedContents["asset"];
    std::string assetGenerator = assetDescription["generator"].asString();
	std::string assetVersion = assetDescription["version"].asString();
    std::cout << "This model is generated by " << assetGenerator << ", version: " << assetVersion << std::endl;

    size_t sceneCount = parsedContents["scenes"].size();
    std::cout << "There is/are " << sceneCount << " scene/s." << std::endl;

    int defaultSceneIndex = parsedContents["scene"].asInt();
    std::cout << "The default scene index is " << defaultSceneIndex << std::endl;

	myJsonFile.close();

	return 0;
}