CUBE_MESH = 0
CONTAINER_MESH = 1
MONKEY_MESH = 2
MIRROR_MESH = 3
MEDKIT_MESH = 4
LIGHT_MESH = 5

WOOD_MATERIAL = 0
MEDKIT_MATERIAL = 1
CLAYBRICK_MATERIAL = 2
HOTEL_WALL_MATERIAL = 3
GLASS_WALL_MATERIAL = 4
PLASTER_MATERIAL = 5
MARBLE_BRASS_MATERIAL = 6
MARBLE_COLD_MATERIAL = 7

LIGHT_MATERIAL = 8

